name: mainにpushされた内容を自動でデプロイ

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Install Clasp
        run: |
          npm init -y
          npm install clasp -g
          npm install jest ts-jest
      - name: Create clasprc.json
        run: |
          echo \{\"token\":\{\"access_token\":\"${{ secrets.CLASP_ACCESS_TOKEN}}\",\"scope\":\"https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/drive.metadata.readonly https://www.googleapis.com/auth/script.projects https://www.googleapis.com/auth/script.webapp.deploy https://www.googleapis.com/auth/logging.read openid https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/drive.file https://www.googleapis.com/auth/script.deployments https://www.googleapis.com/auth/service.management https://www.googleapis.com/auth/cloud-platform\",\"token_type\":\"Bearer\",\"id_token\":\"${{ secrets.CLASP_ID_TOKEN }}\",\"expiry_date\":1620870307822,\"refresh_token\":\"${{ secrets.CLASP_REFRESH_TOKEN }}\"\},\"oauth2ClientSettings\":\{\"clientId\":\"${{ secrets.CLASP_CLIENT_ID }}\",\"clientSecret\":\"${{ secrets.CLASP_CLIENT_SECRET }}\",\"redirectUri\":\"http://localhost\"\},\"isLocalCreds\":false\} > ~/.clasprc.json
      - name: Test
        run: |
          npm run test
      - name: Push
        run: |
          clasp push -f
      - name: Deploy
        run: |
          clasp deploy -i AKfycbz22LCh69kLjRUtxiJIRAknBlC4RUqj8r7GVc4ID59YPjJRWesOL41vMqeyLV5zEx0seA
